cleanups, some packages, helper scripts
Former-commit-id: 463bf91831a4d2ba2fac624280f66388b140940f

diff --git a/alpine/bin/bashbug b/alpine/bin/bashbug
--- a/alpine/bin/bashbug
+++ b/alpine/bin/bashbug
@@ -29,9 +29,9 @@
 MACHINE="x86_64"
 OS="linux-musl"
 CC="gcc"
-CFLAGS=" -DPROGRAM='bash' -DCONF_HOSTTYPE='x86_64' -DCONF_OSTYPE='linux-musl' -DCONF_MACHTYPE='x86_64-alpine-linux-musl' -DCONF_VENDOR='alpine' -DLOCALEDIR='/usr/share/locale' -DPACKAGE='bash' -DSHELL -DHAVE_CONFIG_H   -I.  -I. -I./include -I./lib  -Os -fomit-frame-pointer -Os -fomit-frame-pointer"
-RELEASE="4.3"
-PATCHLEVEL="48"
+CFLAGS=" -DPROGRAM='bash' -DCONF_HOSTTYPE='x86_64' -DCONF_OSTYPE='linux-musl' -DCONF_MACHTYPE='x86_64-alpine-linux-musl' -DCONF_VENDOR='alpine' -DLOCALEDIR='/usr/share/locale' -DPACKAGE='bash' -DSHELL -DHAVE_CONFIG_H   -I.  -I. -I./include -I./lib  -Os -fomit-frame-pointer -Os -fomit-frame-pointer -Wno-parentheses -Wno-format-security"
+RELEASE="4.4"
+PATCHLEVEL="12"
 RELSTATUS="release"
 MACHTYPE="x86_64-alpine-linux-musl"
 
@@ -62,7 +62,7 @@ while [ $# -gt 0 ]; do
 	--version)	shift ; do_version=y ;;
 	--)		shift ; break ;;
 	-*)		echo "bashbug: ${1}: invalid option" >&2
-			echo "$USAGE" >& 2
+			echo "$USAGE" >&2
 			exit 2 ;;
 	*)		break ;;
 	esac
@@ -265,7 +265,8 @@ esac
 
 ${RMAIL} $SMARGS < "$TEMPFILE1" || {
 	cat "$TEMPFILE1" >> $HOME/dead.bashbug
-	echo "$0: mail failed: report saved in $HOME/dead.bashbug" >&2
+	echo "$0: mail to ${BUGADDR} failed: report saved in $HOME/dead.bashbug" >&2
+	echo "$0: please send it manually to ${BUGADDR}" >&2
 }
 
 exit 0
